# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '8'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      mvn --version
      java -version
      pwd
      ls -ltr
      cat ./src/pom.xml
      cat src/pom.xml

- task: Maven@3
  inputs:
    mavenPomFile: './src/pom.xml'
    options: 'install -P scala-2.12_spark-3.1.2'
    publishJUnitResults: false
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/temurin-8-jdk-amd64'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
