# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

stages:

- stage: Generate_jar_files
  displayName: Generating monitoring jar files
  jobs:
  - job: Generate_jar_files
    pool:
      vmImage: ubuntu-latest
    displayName: Running Docker commands
    steps:
    - task: Bash@3
      displayName: Creating profiles
      inputs:
        targetType: inline
        script: |
          set -xeu
          ls -la src/spark-listeners/
          ls -la src/spark-listeners-loganalytics
          ls -la ./build.sh
          chmod +x ./build.sh
          ls -la ./build.sh
          docker --version
          docker run -it --rm -v `pwd`:/spark-monitoring -v "$HOME/.m2":/root/.m2 maven:3.6.3-jdk-8 /spark-monitoring/build.sh
          pwd
          ls -la src/spark-listeners/
          ls -la src/spark-listeners-loganalytics
